package:
  name: pykaldi
  version: "0.0.9"

source:
  git_rev: latest
  git_url: https://github.com/pykaldi/conda-package.git

requirements:
  host:
    - cmake
    - gcc
    - python
    - setuptools
    - numpy
