{% set name = "pykaldi" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/{{ name }}/conda-package.git
  git_rev: v0.0.2

build:
  number: 0
  skip: True #[py<35]
  skip: True #[win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - numpy x.x
    - pip
    - python 3.5*
    - zlib
    - setuptools

test:
  requires:
    - pytest
  imports:
    - pykaldi
  commands:
    - python setup.py test

about:
  home: https://github.com/pykaldi/pykaldi
  license: Apache-2.0
  summary: 'Python wrapper for Kaldi ASR'
  description: |
    PyKaldi is a Python wrapper for Kaldi. It aims to bridge the gap between Kaldi and all the nice things Python has to offer.

  doc_url: https://pykaldi.github.io/
  dev_url: https://github.com/pykaldi/pykaldi

extra:
  recipe-maintainers:
    - vrmpx