{% set name = "pykaldi" %}
{% set version = "0.0.9" %}
{% set hash = "a1ba52f487c0c6e6870fc2b6c7a4c3ac44ebb465" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/pykaldi/pykaldi.git
  git_rev: {{ hash }}

build:
  number: 0
  skip: True #[win]
  skip: True #[py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - openblas 0.2.20|0.2.20*
    - cmake
    - ninja
    - pip
    - python
    - numpy
    - setuptools
    - pytest-runner
  host:
    - zlib
  run:
    - {{ compiler('c') }}
    - openblas 0.2.20|0.2.20.*
    - cmake
    - ninja
    - pip
    - python
    - numpy
    - setuptools
    - pytest-runner

about:
  home: https://github.com/pykaldi/pykaldi.git
  license: Apache-2.0
  summary: 'Python wrapper for Kaldi ASR'
  description: |
    PyKaldi is a Python wrapper for Kaldi. It aims to bridge the gap between Kaldi and all the nice things Python has to offer

extra:
  recipe-maintainers:
    - vrmpx