{% set name = "pykaldi" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/{{ name }}/conda-package.git
  git_rev: b7c82f077f4b2f5501794c10e84b08b9f9c3d7ca

build:
  number: 0
  skip: True #[py<35]
  skip: True #[win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python {{ python }}
    - numpy x.x
    - pip
    - zlib
    - setuptools
    - pytest-runner
  run:
    - python {{ python }}

about:
  home: https://github.com/pykaldi/pykaldi
  license: Apache-2.0
  summary: 'Python wrapper for Kaldi ASR'
  description: |
    PyKaldi is a Python wrapper for Kaldi. It aims to bridge the gap between Kaldi and all the nice things Python has to offer.

  doc_url: https://pykaldi.github.io/
  dev_url: https://github.com/pykaldi/pykaldi

extra:
  recipe-maintainers:
    - vrmpx
