{% set name = "pykaldi" %}
{% set version = "0.0.9" %}
{% set hash = "5510ff91fe0c205652e545b32aa82eb6bc0b266f" %}
{% set number = 7 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/pykaldi/pykaldi.git
  git_rev: {{ hash }}
  patches:
    - CMakeLists.patch # use new locations of the libs for kaldi and openfst
    - install_kaldi.patch # link against openblas
    - setup.patch #force cmake to find python lib
build:
  number: {{ number }} 
  skip: True #[win]

requirements:
  build:
    - {{ compiler('c') }}
    - python {{ python }}
    - cmake
    - ninja
    - setuptools
  host:
    - openblas 0.3.*
    - python {{ python }}
    - pytest-runner
    - numpy 1.15.*
    - enum34 #[py<34]
    - zlib
  run:
    - openblas >=0.3.*
    - python {{ python }}
    - numpy >=1.15 
    - enum34 #[py<34]

about:
  home: https://github.com/pykaldi/pykaldi.git
  license: Apache-2.0
  summary: 'Python wrapper for Kaldi ASR'
  description: |
    PyKaldi is a Python wrapper for Kaldi. It aims to bridge the gap between Kaldi and all the nice things Python has to offer

extra:
  recipe-maintainers:
    - vrmpx
